version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  rebase-strategy: "disabled"
  versioning-strategy: increase-if-necessary
  groups:
    sphinx:
      patterns:
        - "sphinx"
        - "sphinxcontrib*"
- package-ecosystem: github-actions
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: "daily"
