repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.2.2'
    hooks:
    - id: ruff
      types_or: [python, pyi, jupyter, toml]
      args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=no']
  - repo: https://github.com/akaihola/darker
    rev: 1.7.2
    hooks:
      -   id: darker
          args: [-i]
          additional_dependencies: [isort]
