repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.3.5'
    hooks:
    # Run the linter
    - id: ruff
      types_or: [python, pyi, jupyter, toml]
      args: [ --fix, --exit-non-zero-on-fix ]
    # Run the formatter
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=no']
