repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=no']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    - id: pyupgrade
      args: ['--py37-plus', '--keep-runtime-typing']
  - repo: https://github.com/akaihola/darker
    rev: 1.5.1
    hooks:
      -   id: darker
          args: [-i]
          additional_dependencies: [isort]
