# Generated by Django 6.0.1 on 2026-02-12 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AWGStationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "address",
                    models.CharField(
                        default="TCPIP0::192.168.0.2::inst0::INSTR",
                        help_text="VISA address for the AWG",
                        max_length=200,
                    ),
                ),
                (
                    "driver_type",
                    models.CharField(
                        choices=[
                            ("mock", "Mock/Simulation"),
                            ("tektronix_awg70002a", "Tektronix 70002A"),
                            ("tektronix_awg70001a", "Tektronix 70001A"),
                        ],
                        default="mock",
                        help_text="Instrument driver type: 'mock' for simulation or qcodes driver path for real hardware",
                        max_length=200,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="AWG parameters in qcodes Station format",
                    ),
                ),
                (
                    "use_flags",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to use flags when outputting sequence files",
                    ),
                ),
                (
                    "yaml_content",
                    models.TextField(
                        blank=True,
                        help_text="Raw YAML content (for imported configurations)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AWG Station Configuration",
                "verbose_name_plural": "AWG Station Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LUTConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "input_lut",
                    models.JSONField(help_text="List of input values for the LUT"),
                ),
                (
                    "output_lut",
                    models.JSONField(help_text="List of output values for the LUT"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LUT Configuration",
                "verbose_name_plural": "LUT Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScopeStationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "address",
                    models.CharField(
                        default="TCPIP0::192.168.0.3::inst0::INSTR",
                        help_text="VISA address for the Scope",
                        max_length=200,
                    ),
                ),
                (
                    "driver_type",
                    models.CharField(
                        choices=[
                            ("mock", "Mock/Simulation"),
                            ("tektronix_dpo70000", "Tektronix Dpo70000"),
                            ("tektronix_dpo7200", "Tektronix Dpo7200"),
                        ],
                        default="mock",
                        help_text="Instrument driver type: 'mock' for simulation or qcodes driver path for real hardware",
                        max_length=200,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Scope parameters in qcodes Station format",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="List of channel configurations: [{number, coupling, scale, offset, position, enabled}, ...]",
                    ),
                ),
                (
                    "yaml_content",
                    models.TextField(
                        blank=True,
                        help_text="Raw YAML content (for imported configurations)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scope Station Configuration",
                "verbose_name_plural": "Scope Station Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WaveformElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the waveform element", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "element_data",
                    models.JSONField(help_text="Complete broadbean Element JSON"),
                ),
                ("sample_rate", models.FloatField(help_text="Sample rate in Hz")),
                ("duration", models.FloatField(help_text="Total duration in seconds")),
                (
                    "num_channels",
                    models.IntegerField(default=1, help_text="Number of channels"),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if this element was automatically generated (e.g., from parametric sweep)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Waveform Element",
                "verbose_name_plural": "Waveform Elements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaveformSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the sequence", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "sequence_data",
                    models.JSONField(help_text="Complete sequence configuration"),
                ),
                (
                    "total_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Total sequence duration in seconds",
                        null=True,
                    ),
                ),
                (
                    "num_positions",
                    models.IntegerField(
                        default=0, help_text="Number of positions in sequence"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Waveform Sequence",
                "verbose_name_plural": "Waveform Sequences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SequenceElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Position in sequence (1-indexed)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "trigger_input",
                    models.IntegerField(
                        choices=[
                            (0, "Trigger 0"),
                            (1, "Trigger 1"),
                            (2, "Trigger 2"),
                            (3, "Trigger 3"),
                        ],
                        default=0,
                        help_text="Trigger input to wait for (0-3)",
                    ),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=1,
                        help_text="Number of times to repeat this element",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "goto_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Next position to jump to (null for default behavior)",
                        null=True,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        help_text="Channel flags configuration: {channel_1: [A, B, C, D], ...}",
                        null=True,
                    ),
                ),
                (
                    "waveform_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_uses",
                        to="designer.waveformelement",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="designer.waveformsequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sequence Element",
                "verbose_name_plural": "Sequence Elements",
                "ordering": ["sequence", "position"],
                "unique_together": {("sequence", "position")},
            },
        ),
    ]
