# Generated by Django 6.0.2 on 2026-02-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awgstationconfig',
            name='visa_timeout',
            field=models.IntegerField(default=60, help_text='VISA connection timeout in seconds'),
        ),
        migrations.AddField(
            model_name='scopestationconfig',
            name='visa_timeout',
            field=models.IntegerField(default=60, help_text='VISA connection timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='awgstationconfig',
            name='driver_type',
            field=models.CharField(choices=[('mock', 'Mock/Simulation'), ('tektronix_awg70002a', 'Tektronix Awg70002a'), ('tektronix_awg70001a', 'Tektronix Awg70001a')], default='mock', help_text="Instrument driver type: 'mock' for simulation or qcodes driver path for real hardware", max_length=200),
        ),
    ]
