name: Cancel old jobs
on:
  workflow_run:
    workflows:
      - "build docs"
      - "Run mypy and pytest"
      - "Install all deps from conda-forge and run pytest"
      - "CodeQL"
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.11.0
      with:
        all_but_latest: true
        workflow_id: ${{ github.event.workflow.id }}
