name: Install all deps from conda-forge and run pytest

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:

jobs:
  pytestconda:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      DISPLAY: ':99.0'
      OS: ${{ matrix.os }}

    steps:
    - name: checkout source code
      uses: actions/checkout@v3.0.2
      with:
        submodules: true
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: broadbean_forge
        environment-file: .github/static/environment_forge_full.yml
        auto-activate-base: false
    - name: conda info
      shell: bash -l {0}
      run: |
        conda info
    - name: install broadbean
      shell: bash -l {0}
      run: |
        pip install . --no-deps
    - name: Run Mypy
      shell: bash -l {0}
      run: mypy broadbean
    - name: run pytest
      shell: bash -l {0}
      run: |
         pytest --hypothesis-profile ci tests
