name: Lint with Darker

on: [push, pull_request]

jobs:
  lint-with-darker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - uses: akaihola/darker@1.7.1
        with:
          options: "--check --diff"
          src: "./broadbean"
          revision: "origin/main..."
