name: Upload Python Package

on:
  push:
    tags:
      - v*

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: pypi-release-env
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'
    - name: Install build deps
      run: pip install --upgrade pip setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
